version: '3.8'

networks:
  default:
    name: "haji-symfony-demo"
    external: true

services:
  rabbitmq:
    container_name: "haji-symfony-demo-rabbitmq"
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  db:
    container_name: "haji-symfony-demo-db"
    image: mysql:8.3.0
    ports:
      - "3317:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - persistent:/var/lib/mysql
      - ./init-databases:/docker-entrypoint-initdb.d/

volumes:
  persistent: